---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: hans9102/frontapp:10.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:                                                                                                                                                         
  name: front                                                                                                                                                     
spec:                                                                                                                                                             
  type: NodePort                                                                                                                                              
  ports:                                                                                                                                                          
  - port: 80                                                                                                                                                      
    protocol: TCP                                                                                                                                                 
    targetPort: 80                                                                                                                                                
  selector:                                                                                                                                                       
    app: front                                                                                                                                                    
---           

